export interface Vehicle {
  id: string
  slug: string
  name: string
  brand: string
  model: string
  year: number
  price: number
  formattedPrice: string
  mileage: string
  fuelType: string
  transmission: string
  engine: string
  drivetrain: string
  exteriorColor: string
  interiorColor: string
  bodyType: string
  seats: number
  images: string[]
  features: string[]
  description: string
  verified: boolean
  available: boolean
}

export const vehicles: Vehicle[] = [
  {
    id: "1",
    slug: "lexus-lx600-2024",
    name: "Lexus LX 600",
    brand: "Lexus",
    model: "LX 600",
    year: 2024,
    price: 95000000,
    formattedPrice: "₦95,000,000",
    mileage: "8,000 KM",
    fuelType: "Petrol",
    transmission: "Automatic",
    engine: "3.4L V6 Twin-Turbo",
    drivetrain: "4WD",
    exteriorColor: "Black",
    interiorColor: "Tan Leather",
    bodyType: "SUV",
    seats: 7,
    images: ["/images/cars/lexus-lx600.jpg"],
    features: [
      "Mark Levinson Audio",
      "360° Camera",
      "Adaptive Suspension",
      "Premium Leather",
      "Heads-Up Display",
      "Apple CarPlay",
      "Android Auto",
      "Wireless Charging"
    ],
    description: "The Lexus LX 600 represents the pinnacle of luxury SUVs. With its powerful twin-turbo V6 engine and sophisticated all-wheel-drive system, it delivers exceptional performance both on and off-road. The cabin is a sanctuary of premium materials and cutting-edge technology.",
    verified: true,
    available: true
  },
  {
    id: "2",
    slug: "lexus-tx350-2024",
    name: "Lexus TX 350",
    brand: "Lexus",
    model: "TX 350",
    year: 2024,
    price: 75000000,
    formattedPrice: "₦75,000,000",
    mileage: "5,000 KM",
    fuelType: "Petrol",
    transmission: "Automatic",
    engine: "2.4L Turbo",
    drivetrain: "AWD",
    exteriorColor: "Silver",
    interiorColor: "Black Leather",
    bodyType: "SUV",
    seats: 7,
    images: ["/images/cars/lexus-tx350.jpg"],
    features: [
      "14-inch Touchscreen",
      "Lexus Safety System+",
      "Panoramic Roof",
      "Premium Audio",
      "Heated & Cooled Seats",
      "Power Tailgate",
      "Blind Spot Monitor",
      "Parking Assist"
    ],
    description: "The all-new Lexus TX 350 is a three-row luxury SUV that combines elegant design with practical versatility. It offers a refined driving experience with advanced safety features and a spacious interior that accommodates the whole family in comfort.",
    verified: true,
    available: true
  },
  {
    id: "3",
    slug: "mercedes-gle450-2024",
    name: "Mercedes-Benz GLE 450",
    brand: "Mercedes-Benz",
    model: "GLE 450",
    year: 2024,
    price: 85000000,
    formattedPrice: "₦85,000,000",
    mileage: "12,000 KM",
    fuelType: "Petrol",
    transmission: "Automatic",
    engine: "3.0L Inline-6 Turbo",
    drivetrain: "4MATIC",
    exteriorColor: "White",
    interiorColor: "Beige Leather",
    bodyType: "SUV",
    seats: 5,
    images: ["/images/cars/mercedes-gle450.jpg"],
    features: [
      "MBUX Infotainment",
      "Burmester Audio",
      "Air Body Control",
      "64-Color Ambient Lighting",
      "Massage Seats",
      "Augmented Reality Navigation",
      "Active Brake Assist",
      "Parking Package"
    ],
    description: "The Mercedes-Benz GLE 450 combines athletic design with pioneering technology. Its powerful yet efficient engine delivers exhilarating performance, while the luxurious interior features the latest MBUX technology and premium materials throughout.",
    verified: true,
    available: true
  },
  {
    id: "4",
    slug: "mercedes-sclass-2023",
    name: "Mercedes-Benz S-Class",
    brand: "Mercedes-Benz",
    model: "S 580",
    year: 2023,
    price: 150000000,
    formattedPrice: "₦150,000,000",
    mileage: "15,000 KM",
    fuelType: "Petrol",
    transmission: "Automatic",
    engine: "4.0L V8 Biturbo",
    drivetrain: "4MATIC",
    exteriorColor: "Black",
    interiorColor: "Black Nappa Leather",
    bodyType: "Sedan",
    seats: 5,
    images: ["/images/cars/mercedes-sclass.jpg"],
    features: [
      "Rear Axle Steering",
      "E-Active Body Control",
      "Burmester 4D Audio",
      "Executive Rear Seats",
      "Chauffeur Package",
      "Night Vision Assist",
      "Active Distance Assist",
      "OLED Rear Screens"
    ],
    description: "The Mercedes-Benz S-Class is the benchmark for luxury sedans. This flagship model offers unparalleled comfort, groundbreaking technology, and effortless performance. It represents the very best of Mercedes-Benz engineering and craftsmanship.",
    verified: true,
    available: true
  },
  {
    id: "5",
    slug: "range-rover-sport-2024",
    name: "Range Rover Sport",
    brand: "Land Rover",
    model: "Sport P530",
    year: 2024,
    price: 120000000,
    formattedPrice: "₦120,000,000",
    mileage: "10,000 KM",
    fuelType: "Petrol",
    transmission: "Automatic",
    engine: "4.4L V8 Twin-Turbo",
    drivetrain: "AWD",
    exteriorColor: "Gray",
    interiorColor: "Ivory Leather",
    bodyType: "SUV",
    seats: 5,
    images: ["/images/cars/range-rover.jpg"],
    features: [
      "Terrain Response 2",
      "Air Suspension",
      "Meridian Audio",
      "Pixel LED Headlights",
      "Configurable Ambient Lighting",
      "ClearSight Mirror",
      "Activity Key",
      "Gesture Tailgate"
    ],
    description: "The Range Rover Sport delivers an exhilarating drive with dynamic handling and powerful engine options. Its commanding presence is matched by exceptional off-road capability and a luxuriously appointed interior with the latest technology.",
    verified: true,
    available: true
  },
  {
    id: "6",
    slug: "range-rover-velar-2023",
    name: "Range Rover Velar",
    brand: "Land Rover",
    model: "Velar P400",
    year: 2023,
    price: 85000000,
    formattedPrice: "₦85,000,000",
    mileage: "18,000 KM",
    fuelType: "Petrol",
    transmission: "Automatic",
    engine: "3.0L Inline-6 MHEV",
    drivetrain: "AWD",
    exteriorColor: "Silver",
    interiorColor: "Ebony Leather",
    bodyType: "SUV",
    seats: 5,
    images: ["/images/cars/range-rover-velar.jpg"],
    features: [
      "Pivi Pro Infotainment",
      "Wade Sensing",
      "3D Surround Camera",
      "Adaptive Dynamics",
      "Cabin Air Purification",
      "Wireless Charging",
      "Head-Up Display",
      "Electronic Air Suspension"
    ],
    description: "The Range Rover Velar is the avant-garde choice for those who value design as much as capability. Its sleek, modern lines house a refined interior and advanced technology, while maintaining Range Rover's legendary off-road prowess.",
    verified: true,
    available: true
  },
  {
    id: "7",
    slug: "bmw-x5-2024",
    name: "BMW X5 xDrive40i",
    brand: "BMW",
    model: "X5 xDrive40i",
    year: 2024,
    price: 72000000,
    formattedPrice: "₦72,000,000",
    mileage: "7,000 KM",
    fuelType: "Petrol",
    transmission: "Automatic",
    engine: "3.0L Inline-6 Turbo",
    drivetrain: "xDrive AWD",
    exteriorColor: "Blue",
    interiorColor: "Cognac Leather",
    bodyType: "SUV",
    seats: 5,
    images: ["/images/cars/bmw-x5.jpg"],
    features: [
      "Live Cockpit Professional",
      "Harman Kardon Audio",
      "Panoramic Sky Lounge LED",
      "Gesture Control",
      "Driving Assistant Pro",
      "Comfort Access",
      "Soft Close Doors",
      "Heated Steering Wheel"
    ],
    description: "The BMW X5 sets the standard for Sports Activity Vehicles with its dynamic driving characteristics and luxurious appointments. It combines BMW's signature driving pleasure with practical versatility and advanced technology.",
    verified: true,
    available: true
  },
  {
    id: "8",
    slug: "audi-q8-2024",
    name: "Audi Q8 Premium Plus",
    brand: "Audi",
    model: "Q8 55 TFSI",
    year: 2024,
    price: 78000000,
    formattedPrice: "₦78,000,000",
    mileage: "9,000 KM",
    fuelType: "Petrol",
    transmission: "Automatic",
    engine: "3.0L V6 TFSI",
    drivetrain: "quattro AWD",
    exteriorColor: "Gray",
    interiorColor: "Black Valcona Leather",
    bodyType: "SUV",
    seats: 5,
    images: ["/images/cars/audi-q8.jpg"],
    features: [
      "MMI Touch Response",
      "Bang & Olufsen Audio",
      "Matrix LED Headlights",
      "Virtual Cockpit Plus",
      "Adaptive Air Suspension",
      "360° Cameras",
      "Night Vision",
      "Adaptive Cruise Control"
    ],
    description: "The Audi Q8 is a statement of progressive design and sophisticated technology. Its coupe-like silhouette houses a spacious interior with dual touchscreen displays and Audi's latest driver assistance features.",
    verified: true,
    available: true
  },
  {
    id: "9",
    slug: "toyota-land-cruiser-300-2024",
    name: "Toyota Land Cruiser 300",
    brand: "Toyota",
    model: "Land Cruiser 300 VX",
    year: 2024,
    price: 115000000,
    formattedPrice: "₦115,000,000",
    mileage: "5,000 KM",
    fuelType: "Diesel",
    transmission: "Automatic",
    engine: "3.3L V6 Twin-Turbo Diesel",
    drivetrain: "4WD",
    exteriorColor: "White",
    interiorColor: "Brown Leather",
    bodyType: "SUV",
    seats: 7,
    images: ["/images/cars/toyota-lc300.jpg"],
    features: [
      "Multi-Terrain Select",
      "Crawl Control",
      "JBL Premium Audio",
      "12.3-inch Display",
      "Toyota Safety Sense",
      "Fingerprint Authentication",
      "E-KDSS",
      "Rear Entertainment"
    ],
    description: "The legendary Toyota Land Cruiser 300 continues its legacy of unmatched reliability and off-road capability. With its new platform and powerful diesel engine, it delivers both rugged performance and refined luxury.",
    verified: true,
    available: true
  },
  {
    id: "10",
    slug: "toyota-prado-2023",
    name: "Toyota Land Cruiser Prado",
    brand: "Toyota",
    model: "Prado VX",
    year: 2023,
    price: 65000000,
    formattedPrice: "₦65,000,000",
    mileage: "20,000 KM",
    fuelType: "Petrol",
    transmission: "Automatic",
    engine: "2.7L Inline-4",
    drivetrain: "4WD",
    exteriorColor: "White",
    interiorColor: "Beige Leather",
    bodyType: "SUV",
    seats: 7,
    images: ["/images/cars/toyota-prado.jpg"],
    features: [
      "Multi-Terrain Monitor",
      "Kinetic Dynamic Suspension",
      "9-inch Touchscreen",
      "JBL Audio",
      "Pre-Collision System",
      "Lane Departure Alert",
      "Adaptive Cruise Control",
      "Cool Box"
    ],
    description: "The Toyota Land Cruiser Prado is the versatile choice for those who need both daily comfort and weekend adventure capability. It combines legendary Toyota reliability with modern features and timeless design.",
    verified: true,
    available: true
  },
  {
    id: "11",
    slug: "porsche-cayenne-2024",
    name: "Porsche Cayenne",
    brand: "Porsche",
    model: "Cayenne S",
    year: 2024,
    price: 130000000,
    formattedPrice: "₦130,000,000",
    mileage: "6,000 KM",
    fuelType: "Petrol",
    transmission: "Automatic",
    engine: "4.0L V8 Twin-Turbo",
    drivetrain: "AWD",
    exteriorColor: "Red",
    interiorColor: "Black Leather",
    bodyType: "SUV",
    seats: 5,
    images: ["/images/cars/porsche-cayenne.jpg"],
    features: [
      "Porsche Active Suspension",
      "Sport Chrono Package",
      "Bose Audio",
      "Porsche Dynamic Light System",
      "Adaptive Air Suspension",
      "Panoramic Roof",
      "14-Way Sport Seats",
      "Lane Change Assist"
    ],
    description: "The Porsche Cayenne S delivers sports car performance in an SUV package. Its twin-turbo V8 provides breathtaking acceleration while the chassis offers the dynamic handling Porsche is famous for.",
    verified: true,
    available: true
  },
  {
    id: "12",
    slug: "infiniti-qx80-2024",
    name: "Infiniti QX80",
    brand: "Infiniti",
    model: "QX80 Sensory",
    year: 2024,
    price: 88000000,
    formattedPrice: "₦88,000,000",
    mileage: "11,000 KM",
    fuelType: "Petrol",
    transmission: "Automatic",
    engine: "5.6L V8",
    drivetrain: "4WD",
    exteriorColor: "Black",
    interiorColor: "Wheat Leather",
    bodyType: "SUV",
    seats: 7,
    images: ["/images/cars/infiniti-qx80.jpg"],
    features: [
      "Theatre Package",
      "Bose Audio",
      "ProPILOT Assist",
      "Hydraulic Body Motion Control",
      "Around View Monitor",
      "Semi-Aniline Leather",
      "Wireless Charging",
      "Climate-Controlled Seats"
    ],
    description: "The Infiniti QX80 is a full-size luxury SUV that combines commanding presence with refined comfort. Its powerful V8 engine and spacious three-row interior make it perfect for those who demand the best.",
    verified: true,
    available: true
  },
  {
    id: "13",
    slug: "honda-accord-2024",
    name: "Honda Accord Touring",
    brand: "Honda",
    model: "Accord Touring",
    year: 2024,
    price: 32000000,
    formattedPrice: "₦32,000,000",
    mileage: "8,000 KM",
    fuelType: "Petrol",
    transmission: "CVT",
    engine: "2.0L Turbo",
    drivetrain: "FWD",
    exteriorColor: "Red",
    interiorColor: "Black Leather",
    bodyType: "Sedan",
    seats: 5,
    images: ["/images/cars/honda-accord.jpg"],
    features: [
      "Google Built-In",
      "Bose Premium Audio",
      "Honda Sensing",
      "Wireless CarPlay",
      "Head-Up Display",
      "Ventilated Seats",
      "Wireless Charging",
      "Traffic Jam Assist"
    ],
    description: "The Honda Accord Touring represents the perfect blend of sophistication, technology, and reliability. Its turbocharged engine delivers spirited performance while maintaining excellent fuel efficiency.",
    verified: true,
    available: true
  },
  {
    id: "14",
    slug: "gmc-yukon-denali-2024",
    name: "GMC Yukon Denali",
    brand: "GMC",
    model: "Yukon Denali Ultimate",
    year: 2024,
    price: 105000000,
    formattedPrice: "₦105,000,000",
    mileage: "9,000 KM",
    fuelType: "Petrol",
    transmission: "Automatic",
    engine: "6.2L V8",
    drivetrain: "4WD",
    exteriorColor: "Black",
    interiorColor: "Alpine Leather",
    bodyType: "SUV",
    seats: 7,
    images: ["/images/cars/gmc-yukon.jpg"],
    features: [
      "Super Cruise",
      "Magnetic Ride Control",
      "16-Speaker Bose Audio",
      "Air Ride Adaptive Suspension",
      "Rear Seat Entertainment",
      "Power Sliding Console",
      "Night Vision",
      "Head-Up Display"
    ],
    description: "The GMC Yukon Denali Ultimate is the pinnacle of full-size luxury SUVs. With its powerful V8 engine, advanced Super Cruise technology, and first-class interior appointments, it redefines what an SUV can be.",
    verified: true,
    available: true
  },
  {
    id: "15",
    slug: "cadillac-escalade-2024",
    name: "Cadillac Escalade ESV",
    brand: "Cadillac",
    model: "Escalade ESV Premium",
    year: 2024,
    price: 140000000,
    formattedPrice: "₦140,000,000",
    mileage: "7,000 KM",
    fuelType: "Petrol",
    transmission: "Automatic",
    engine: "6.2L V8",
    drivetrain: "4WD",
    exteriorColor: "Blue",
    interiorColor: "Whisper Beige",
    bodyType: "SUV",
    seats: 7,
    images: ["/images/cars/cadillac-escalade.jpg"],
    features: [
      "38-inch Curved OLED Display",
      "AKG Studio Audio",
      "Super Cruise",
      "Air Ride Suspension",
      "Night Vision",
      "Rear Camera Mirror",
      "Magnetic Ride Control",
      "Performance Data Recorder"
    ],
    description: "The Cadillac Escalade ESV is an icon of American luxury. Its extended wheelbase provides exceptional passenger space, while the curved OLED display and AKG audio system deliver a truly immersive experience.",
    verified: true,
    available: true
  },
  {
    id: "16",
    slug: "bentley-bentayga-2023",
    name: "Bentley Bentayga",
    brand: "Bentley",
    model: "Bentayga V8",
    year: 2023,
    price: 250000000,
    formattedPrice: "₦250,000,000",
    mileage: "5,000 KM",
    fuelType: "Petrol",
    transmission: "Automatic",
    engine: "4.0L V8 Twin-Turbo",
    drivetrain: "AWD",
    exteriorColor: "Green",
    interiorColor: "Linen Leather",
    bodyType: "SUV",
    seats: 5,
    images: ["/images/cars/bentley-bentayga.jpg"],
    features: [
      "Naim for Bentley Audio",
      "Bentley Dynamic Ride",
      "Night Vision",
      "Bentley Rotating Display",
      "Diamond Knurling",
      "Mood Lighting",
      "All-Terrain Specification",
      "Touring Specification"
    ],
    description: "The Bentley Bentayga is the definitive luxury SUV. Hand-crafted in Crewe, England, it combines breathtaking performance with exquisite craftsmanship and materials of the highest quality.",
    verified: true,
    available: true
  }
]

export const brands = [
  { name: "Mercedes-Benz", logo: "/images/brands/mercedes.jpg", count: 2 },
  { name: "BMW", logo: "/images/brands/bmw.jpg", count: 1 },
  { name: "Lexus", logo: "/images/brands/lexus.jpg", count: 2 },
  { name: "Land Rover", logo: "/images/brands/range-rover.jpg", count: 2 },
  { name: "Toyota", logo: "/images/brands/toyota.jpg", count: 2 },
  { name: "Porsche", logo: "/images/brands/porsche.jpg", count: 1 },
  { name: "Audi", logo: "/images/brands/audi.jpg", count: 1 },
  { name: "Infiniti", logo: "/images/brands/infiniti.jpg", count: 1 },
  { name: "Honda", logo: "/images/brands/honda.jpg", count: 1 },
  { name: "Bentley", logo: "/images/brands/bentley.jpg", count: 1 },
  { name: "Cadillac", logo: "/images/brands/cadillac.jpg", count: 1 },
  { name: "GMC", logo: "/images/brands/gmc.jpg", count: 1 },
  { name: "Kia", logo: "/images/brands/kia.svg", count: 0 },
]

export function getVehicleBySlug(slug: string): Vehicle | undefined {
  return vehicles.find(v => v.slug === slug)
}

export function getVehiclesByBrand(brand: string): Vehicle[] {
  return vehicles.filter(v => v.brand === brand)
}
